import "./functions/health.js";
import "./functions/config.js";
import "./functions/challenge.js";
import "./functions/mapsToken.js";
import "./functions/reportsCreate.js";
import "./functions/search.js";
import "./functions/reportGet.js";
import "./functions/reportEvents.js";
import "./functions/reportOwnerEvents.js";
